apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-cstorclusterconfig
  namespace: cstorpoolauto
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
    updateStrategy:
      method: InPlace
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: nodes
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterconfig