---
# This StatefulSet deploys cstorpoolauto server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.mayadata.io/name: cstorpoolauto
  name: cstorpoolauto
  namespace: openebs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.mayadata.io/name: cstorpoolauto
  serviceName: ""
  template:
    metadata:
      labels:
        app.mayadata.io/name: cstorpoolauto
    spec:
      serviceAccountName: cstorpoolauto
      containers:
      - name: cstorpoolauto
        image: quay.io/amitkumardas/cstorpoolauto:latest
        command: ["/usr/bin/cstorpoolauto"]
        args:
        - --logtostderr
        - --run-as-local
        - -v=4
        - --discovery-interval=40s
        - --cache-flush-interval=240s
---