---
# This deployment deploys cstorpoolauto server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstorpoolauto
  namespace: dao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cstorpoolauto
  template:
    metadata:
      labels:
        app: cstorpoolauto
    spec:
      containers:
      - name: server
        image: quay.io/amitkumardas/cstorpoolauto:latest
        command: ["cstorpoolauto"]
---
# This is the corresponding Kubernetes service
# of cstorpoolauto server. Consumers of cstorpoolauto
# server will make use of this service namespace, name
# & port to communicate to cstorpoolauto server.
apiVersion: v1
kind: Service
metadata:
  name: cstorpoolauto
  namespace: dao
spec:
  selector:
    app: cstorpoolauto
  ports:
  - port: 80
    targetPort: 8080