apiVersion: v1
kind: ServiceAccount
metadata:
  name: cstorpoolauto
  namespace: dao
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cstorpoolauto
rules:
- apiGroups:
  - "*"
  resources:
  - cstorclusterconfigs
  - cstorclusterplans
  - cstorclusterstoragesets
  - storages
  - persistentvolumeclaims
  - blockdevices
  - cstorpoolclusters
  - nodes
  verbs:
  - get
  - list
  - watch
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cstorpoolauto
subjects:
- kind: ServiceAccount
  name: cstorpoolauto
  namespace: dao
roleRef:
  kind: ClusterRole
  name: cstorpoolauto
  apiGroup: rbac.authorization.k8s.io
---