apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-localdevice
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  attachments:
  - apiVersion: openebs.io/v1alpha1
    resource: blockdevices
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpoolclusters
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      # select CStorPoolCluster resources if its annotation
      # has both the following
      - matchAnnotations:
          dao.mayadata.io/cstorclusterconfig-localdisk: "true"
        matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/cstorclusterconfig-uid
          refKey: metadata.uid # match this ann value against watch UID
  hooks:
    # controller gets triggered through this hook when 
    # CStorClusterConfig gets created or modified
    sync:
      inline:
        funcName: sync/localdevice
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: finalize-localdevice
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  attachments:
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpoolclusters
    advancedSelector:
      selectorTerms:
      # select CStorPoolCluster resources if its annotation
      # has both the following
      - matchAnnotations:
          dao.mayadata.io/cstorclusterconfig-localdisk: "true"
        matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/cstorclusterconfig-uid
          refKey: metadata.uid # match this ann value against watch UID
  hooks:
    # controller gets triggered through this hook only when 
    # CStorClusterConfig (i.e. watch) is deleted
    finalize:
      inline:
        funcName: finalize/localdevice
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-config
  namespace: cspauto
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
    updateStrategy:
      method: InPlace
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: nodes
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterconfig
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-plan
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
    updateStrategy:
      method: InPlace
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterplan
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-storageset
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: storages
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterstorageset
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-blockdevice
  namespace: cspauto
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: storages
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  - apiVersion: openebs.io/v1alpha1
    resource: blockdevices
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: persistentvolumeclaims
  hooks:
    sync:
      inline:
        funcName: sync/blockdevice
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-cspc
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
  attachments:
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpoolclusters
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: blockdevices
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  hooks:
    sync:
      inline:
        funcName: sync/cstorpoolcluster
---