apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-cstorclusterconfig
  namespace: cstorpoolauto
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
    updateStrategy:
      method: InPlace
    - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: nodes
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterconfig
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-cstorclusterplan
  namespace: cstorpoolauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterplan
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-cstorclusterstorageset
  namespace: cstorpoolauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: storages
  hooks:
    sync:
      inline:
        funcName: sync/cstorclusterstorageset
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-blockdevice
  namespace: cstorpoolauto
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: storages
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  - apiVersion: openebs.io/v1alpha1
    resource: blockdevices
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: persistentvolumeclaims
  hooks:
    sync:
      inline:
        funcName: sync/blockdevice
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-cstorpoolcluster
  namespace: cstorpoolauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterplans
  attachments:
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpoolclusters
  - apiVersion: openebs.io/v1alpha1
    resource: blockdevices
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterstoragesets
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  hooks:
    sync:
      inline:
        funcName: sync/cstorpoolcluster
---