apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-localdevice
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  attachments:
  - apiVersion: openebs.io/v1alpha1
    resource: blockdevices
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpoolclusters
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      # select CStorPoolCluster resources if its annotation
      # has both the following
      - matchAnnotations:
          dao.mayadata.io/cstorclusterconfig-localdisk: "true"
        matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/cstorclusterconfig-uid
          refKey: metadata.uid # match this ann value against watch UID
  hooks:
    # controller gets triggered through this hook when 
    # CStorClusterConfig gets created or modified
    sync:
      inline:
        funcName: sync/localdevice
---
apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: finalize-localdevice
  namespace: cspauto
spec:
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: cstorclusterconfigs
  attachments:
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpoolclusters
    advancedSelector:
      selectorTerms:
      # select CStorPoolCluster resources if its annotation
      # has both the following
      - matchAnnotations:
          dao.mayadata.io/cstorclusterconfig-localdisk: "true"
        matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/cstorclusterconfig-uid
          refKey: metadata.uid # match this ann value against watch UID
  hooks:
    # controller gets triggered through this hook only when 
    # CStorClusterConfig (i.e. watch) is deleted
    finalize:
      inline:
        funcName: finalize/localdevice
---